# coding: utf-8

"""
    NamSor API v2

    NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 1000 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it!   # noqa: E501

    OpenAPI spec version: 2.0.2-beta
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.chinese_api import ChineseApi  # noqa: E501
from openapi_client.rest import ApiException


class TestChineseApi(unittest.TestCase):
    """ChineseApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.chinese_api.ChineseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_chinese_name_candidates(self):
        """Test case for chinese_name_candidates

        Identify Chinese name candidates, based on the romanized name.  # noqa: E501
        """
        pass

    def test_chinese_name_candidates_batch(self):
        """Test case for chinese_name_candidates_batch

        Identify Chinese name candidates, based on the romanized name (firstName = chineseGivenName; lastName=chineseSurname).  # noqa: E501
        """
        pass

    def test_chinese_name_candidates_gender_batch(self):
        """Test case for chinese_name_candidates_gender_batch

        Identify Chinese name candidates, based on the romanized name (firstName = chineseGivenName; lastName=chineseSurname).  # noqa: E501
        """
        pass

    def test_chinese_name_gender_candidates(self):
        """Test case for chinese_name_gender_candidates

        Identify Chinese name candidates, based on the romanized name - having a known gender ('male' or 'female')  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
