# coding: utf-8

"""
    NamSor API v2

    NamSor API v2 : enpoints to process personal names (gender, cultural origin or ethnicity) in all alphabets or languages. Use GET methods for small tests, but prefer POST methods for higher throughput (batch processing of up to 100 names at a time). Need something you can't find here? We have many more features coming soon. Let us know, we'll do our best to add it!   # noqa: E501

    OpenAPI spec version: 2.0.12
    Contact: contact@namsor.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PersonalNameGenderedOut(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'script': 'str',
        'id': 'str',
        'name': 'str',
        'likely_gender': 'str',
        'gender_scale': 'float',
        'score': 'float',
        'probability_calibrated': 'float',
        'category': 'str'
    }

    attribute_map = {
        'script': 'script',
        'id': 'id',
        'name': 'name',
        'likely_gender': 'likelyGender',
        'gender_scale': 'genderScale',
        'score': 'score',
        'probability_calibrated': 'probabilityCalibrated',
        'category': 'category'
    }

    def __init__(self, script=None, id=None, name=None, likely_gender=None, gender_scale=None, score=None, probability_calibrated=None, category=None):  # noqa: E501
        """PersonalNameGenderedOut - a model defined in OpenAPI"""  # noqa: E501

        self._script = None
        self._id = None
        self._name = None
        self._likely_gender = None
        self._gender_scale = None
        self._score = None
        self._probability_calibrated = None
        self._category = None
        self.discriminator = None

        if script is not None:
            self.script = script
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if likely_gender is not None:
            self.likely_gender = likely_gender
        if gender_scale is not None:
            self.gender_scale = gender_scale
        if score is not None:
            self.score = score
        if probability_calibrated is not None:
            self.probability_calibrated = probability_calibrated
        if category is not None:
            self.category = category

    @property
    def script(self):
        """Gets the script of this PersonalNameGenderedOut.  # noqa: E501


        :return: The script of this PersonalNameGenderedOut.  # noqa: E501
        :rtype: str
        """
        return self._script

    @script.setter
    def script(self, script):
        """Sets the script of this PersonalNameGenderedOut.


        :param script: The script of this PersonalNameGenderedOut.  # noqa: E501
        :type: str
        """

        self._script = script

    @property
    def id(self):
        """Gets the id of this PersonalNameGenderedOut.  # noqa: E501


        :return: The id of this PersonalNameGenderedOut.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this PersonalNameGenderedOut.


        :param id: The id of this PersonalNameGenderedOut.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this PersonalNameGenderedOut.  # noqa: E501


        :return: The name of this PersonalNameGenderedOut.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PersonalNameGenderedOut.


        :param name: The name of this PersonalNameGenderedOut.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def likely_gender(self):
        """Gets the likely_gender of this PersonalNameGenderedOut.  # noqa: E501

        Most likely gender  # noqa: E501

        :return: The likely_gender of this PersonalNameGenderedOut.  # noqa: E501
        :rtype: str
        """
        return self._likely_gender

    @likely_gender.setter
    def likely_gender(self, likely_gender):
        """Sets the likely_gender of this PersonalNameGenderedOut.

        Most likely gender  # noqa: E501

        :param likely_gender: The likely_gender of this PersonalNameGenderedOut.  # noqa: E501
        :type: str
        """
        allowed_values = ["male", "female", "unknown"]  # noqa: E501
        if likely_gender not in allowed_values:
            raise ValueError(
                "Invalid value for `likely_gender` ({0}), must be one of {1}"  # noqa: E501
                .format(likely_gender, allowed_values)
            )

        self._likely_gender = likely_gender

    @property
    def gender_scale(self):
        """Gets the gender_scale of this PersonalNameGenderedOut.  # noqa: E501

        Compatibility to NamSor_v1 Gender Scale M[-1..U..+1]F value  # noqa: E501

        :return: The gender_scale of this PersonalNameGenderedOut.  # noqa: E501
        :rtype: float
        """
        return self._gender_scale

    @gender_scale.setter
    def gender_scale(self, gender_scale):
        """Sets the gender_scale of this PersonalNameGenderedOut.

        Compatibility to NamSor_v1 Gender Scale M[-1..U..+1]F value  # noqa: E501

        :param gender_scale: The gender_scale of this PersonalNameGenderedOut.  # noqa: E501
        :type: float
        """

        self._gender_scale = gender_scale

    @property
    def score(self):
        """Gets the score of this PersonalNameGenderedOut.  # noqa: E501


        :return: The score of this PersonalNameGenderedOut.  # noqa: E501
        :rtype: float
        """
        return self._score

    @score.setter
    def score(self, score):
        """Sets the score of this PersonalNameGenderedOut.


        :param score: The score of this PersonalNameGenderedOut.  # noqa: E501
        :type: float
        """

        self._score = score

    @property
    def probability_calibrated(self):
        """Gets the probability_calibrated of this PersonalNameGenderedOut.  # noqa: E501


        :return: The probability_calibrated of this PersonalNameGenderedOut.  # noqa: E501
        :rtype: float
        """
        return self._probability_calibrated

    @probability_calibrated.setter
    def probability_calibrated(self, probability_calibrated):
        """Sets the probability_calibrated of this PersonalNameGenderedOut.


        :param probability_calibrated: The probability_calibrated of this PersonalNameGenderedOut.  # noqa: E501
        :type: float
        """

        self._probability_calibrated = probability_calibrated

    @property
    def category(self):
        """Gets the category of this PersonalNameGenderedOut.  # noqa: E501


        :return: The category of this PersonalNameGenderedOut.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this PersonalNameGenderedOut.


        :param category: The category of this PersonalNameGenderedOut.  # noqa: E501
        :type: str
        """

        self._category = category

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PersonalNameGenderedOut):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
