from openapi_client.paths.api2_json_japanese_name_match_feedback_loop_japanese_surname_latin_japanese_given_name_latin_japanese_name.get import ApiForget


class Api2JsonJapaneseNameMatchFeedbackLoopJapaneseSurnameLatinJapaneseGivenNameLatinJapaneseName(
    ApiForget,
):
    pass
