from openapi_client.paths.api2_json_japanese_name_kanji_candidates_japanese_surname_latin_japanese_given_name_latin_known_gender.get import ApiForget


class Api2JsonJapaneseNameKanjiCandidatesJapaneseSurnameLatinJapaneseGivenNameLatinKnownGender(
    ApiForget,
):
    pass
