from openapi_client.paths.api2_json_chinese_name_gender_candidates_chinese_surname_latin_chinese_given_name_latin_known_gender.get import ApiForget


class Api2JsonChineseNameGenderCandidatesChineseSurnameLatinChineseGivenNameLatinKnownGender(
    ApiForget,
):
    pass
